Repository BinaryStudioAcademy/bsa-2021-jabber, pull requests merged in 2021-07, with the labels that each got.

#8 Task-J10: Added class modifier
  backend/src/data/repositories/user/user.repository.ts
  backend/src/services/auth/auth.service.ts
  backend/src/services/logger/logger.service.ts
  backend/src/services/user/user.service.ts
  frontend/src/services/auth-api/auth-api.service.ts
  frontend/src/services/http/http.service.ts
Labels: mergeable

#10 Task tm/j 20 remove redux toolkit boilerplate clutter
  .gitignore
  frontend/src/assets/img/logo.svg
  frontend/src/components/app/app.tsx
  frontend/src/components/counter/counter.tsx
  frontend/src/components/counter/styles.module.scss
  frontend/src/components/sign-in/sign-in.tsx
  frontend/src/components/sign-up/sign-up.tsx
  frontend/src/store/actions.ts
  frontend/src/store/counter/actions.ts
  frontend/src/store/counter/common.ts
  frontend/src/store/counter/reducer.ts
  frontend/src/store/root-reducer.ts
Labels: mergeable

#14 Task yc/j14 add header
  frontend/public/index.html
  frontend/src/assets/css/styles.scss
  frontend/src/assets/img/default-user-avatar.svg
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/header/styles.module.scss
  frontend/src/components/common/link/link.tsx
  frontend/src/store/auth/reducer.ts
Labels: enhancement, merge conflicts

#23 Add not found page and connect it to router
  frontend/src/assets/img/logo-cut.svg
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/not-found/not-found.tsx
  frontend/src/components/common/not-found/styles.module.scss
Labels: enhancement
