Repository BinaryStudioAcademy/bsa-2021-jabber, pull requests merged in 2021-08, with the labels that each got.

#24 Task tm/j 13 home page client markup
  frontend/src/assets/img/temporary-cover.jpg
  frontend/src/components/app/app.tsx
  frontend/src/components/common/button/button.tsx
  frontend/src/components/home-page/components/components.ts
  frontend/src/components/home-page/components/podcast/podcast.tsx
  frontend/src/components/home-page/components/podcast/styles.module.scss
  frontend/src/components/home-page/components/podcasts-list/podcasts-list.tsx
  frontend/src/components/home-page/components/podcasts-list/styles.module.scss
  frontend/src/components/home-page/home-page.tsx
  frontend/src/components/home-page/styles.module.scss
Labels: merge conflicts

#58 Task ys/j44 create episode page
  frontend/src/common/constants/constants.ts
  frontend/src/common/constants/podcast/podcast.ts
  frontend/src/common/enums/app/app-route.enum.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/episode/episode.ts
  frontend/src/components/app/app.tsx
  frontend/src/components/common/common.ts
  frontend/src/components/common/select/select.tsx
  frontend/src/components/common/select/styles.module.scss
  frontend/src/components/configurate-episode/common/types/page-params.type.ts
  frontend/src/components/configurate-episode/common/types/types.ts
  frontend/src/components/configurate-episode/components/components.ts
  frontend/src/components/configurate-episode/components/create-episode-form/common/constants.ts
  frontend/src/components/configurate-episode/components/create-episode-form/create-episode-form.tsx
  frontend/src/components/configurate-episode/components/create-episode-form/styles.module.scss
  frontend/src/components/configurate-episode/configurate-episode.tsx
  frontend/src/store/actions.ts
  frontend/src/store/configurate-episode/actions.ts
  frontend/src/store/configurate-episode/common.ts
  frontend/src/store/configurate-episode/reducer.ts
  frontend/src/store/episode/common.ts
  frontend/src/store/root-reducer.ts
  shared/src/common/constants/constants.ts
  shared/src/common/constants/podcast/podcast.ts
Labels: merge conflicts

#64 Task-J69: fixed styles validation errors
  frontend/src/components/auth/components/sign-up-form/styles.module.scss
  frontend/src/components/common/input/styles.module.scss
Labels: mergeable

#80 Fix empty validations for user name & etc
  shared/src/validation-schemas/user/sign-in/sign-in.validation-schema.ts
  shared/src/validation-schemas/user/sign-up/sign-up.validation-schema.ts
Labels: ASAP

#85 J85: + enum-type-to-podcasts-table
  backend/src/common/enums/db/podcast-dto-key.enum.ts
  backend/src/common/enums/enums.ts
  backend/src/common/enums/podcast/podcast.ts
  backend/src/common/types/podcast/podcast-create-dto-payload.type.ts
  backend/src/data/migrations/20210805155531_add_type_to_podcasts.ts
  backend/src/data/models/podcast/podcast.model.ts
  backend/src/services/podcast/podcast.service.ts
  backend/src/validation-schemas/podcast/create-podcast/create-podcast.validation-schema.ts
  frontend/src/common/enums/enums.ts
  frontend/src/common/enums/podcast/podcast.ts
  frontend/src/components/configurate-podcast/components/configurate-podcast-form/common/constants.ts
  frontend/src/components/configurate-podcast/helpers/map-podcast-to-form-payload/map-podcast-to-form-payload.ts
  frontend/src/store/configurate-podcast/actions.ts
  shared/src/common/enums/enums.ts
  shared/src/common/enums/podcast/podcast-payload-key.enum.ts
  shared/src/common/enums/podcast/podcast-type.enum.ts
  shared/src/common/enums/podcast/podcast.ts
  shared/src/common/types/podcast/podcast-payload.type.ts
  shared/src/common/types/podcast/podcast.type.ts
Labels: merge conflicts

#92 bugfix: * update-podcast-validation-schema
  backend/src/validation-schemas/podcast/create-podcast/create-podcast.validation-schema.ts
  shared/src/validation-schemas/podcast/podcast.validation-schema.ts
Labels: bug

#138 task-sf/J138-fix-functional-update-record-in-edit-episode
  backend/src/services/episode/episode.service.ts
Labels: bug

#143 Task sf/j139 bugfix fix edit podcast functional
  backend/src/common/types/podcast/podcast-edit-dto-payload.type.ts
  backend/src/services/podcast/podcast.service.ts
  backend/src/validation-schemas/podcast/edit-podcast/edit-podcast.validation-schema.ts
  frontend/src/services/podcast-api/podcast-api.service.ts
  frontend/src/store/configurate-podcast/actions.ts
  shared/src/common/types/podcast/podcast-edit-payload.type.ts
Labels: bug

#245 Task yc/j222 add library for popuper to handle screen overlapping
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/css/scaffolding.scss
  frontend/src/components/common/common.ts
  frontend/src/components/common/header/header.tsx
  frontend/src/components/common/header/styles.module.scss
  frontend/src/components/common/popuper/popuper.tsx
Labels: merge conflicts

#270 bugfix/fix-homepage-reducer
  frontend/src/store/homepage/reducer.ts
Labels: bug

#324 Fix av/j272 reset user password without email confirmation
  backend/src/services/auth/auth.service.ts
Labels: bug

#327 Fix av/j303 only owner can see copy invite code button
  frontend/src/components/podcast/podcast.tsx
Labels: bug

#331 Fix av/j311 fix when the user press enter in the search bar the-page reloads without searching
  frontend/src/components/homepage/components/search/search.tsx
Labels: bug
